name: Auto Assign

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    uses: wspulse/.github/.github/workflows/auto-assign.yml@main
    permissions:
      issues: write
      pull-requests: write
